# Generated by Django 4.2.4 on 2023-10-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="name",
            field=models.CharField(default="General Hospital", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hospital",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="nta",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
