# Generated by Django 4.2.3 on 2023-10-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalappointment',
            name='assigned_doctor',
        ),
        migrations.RemoveField(
            model_name='hospitalappointment',
            name='end_time',
        ),
        migrations.AddField(
            model_name='hospitalappointment',
            name='accebility',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='hospitalappointment',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalappointment',
            name='name',
            field=models.CharField(default='James', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalappointment',
            name='phone',
            field=models.CharField(default='7483684947', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalappointment',
            name='reason',
            field=models.CharField(default='Flu Shot', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
