# Generated by Django 4.2.4 on 2023-10-17 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0002_hospital_name_alter_hospital_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="nta",
        ),
    ]
