# Generated by Django 4.2.4 on 2023-10-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('practice_name', models.CharField(max_length=100)),
                ('primary_speciality', models.CharField(max_length=50)),
                ('site_name', models.CharField(max_length=100)),
                ('practice_borough', models.CharField(max_length=50)),
                ('practice_mailing_address', models.CharField(max_length=200)),
                ('practice_phone_number', models.CharField(max_length=12)),
                ('organization_type', models.CharField(max_length=100)),
                ('practice_zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('REQ', 'Requested'), ('CNF', 'Confirmed'), ('CCL', 'Cancelled')], max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
