# Generated by Django 4.2.5 on 2023-10-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="example@example.com", max_length=254, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="example@example.com", max_length=100),
        ),
    ]
