# Generated by Django 4.2.4 on 2023-10-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_patient_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
    ]
