# Generated by Django 4.2.5 on 2023-11-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_patient_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
