# Generated by Django 4.2.5 on 2023-11-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_hospitaladmin_active_status'),
        ('user', '0011_doctor_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_reviews',
            old_name='doctor',
            new_name='doctor_name',
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Name', max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254, unique=True)),
                ('phone', models.CharField(default='000-000-0000', max_length=15)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('address', models.CharField(max_length=200)),
                ('borough', models.CharField(choices=[('BKN', 'Brooklyn'), ('MHT', 'Manhattan'), ('QNS', 'Queens'), ('BRX', 'Bronx'), ('SND', 'Staten Island')], max_length=50)),
                ('zip', models.IntegerField()),
                ('avatar', models.ImageField(blank=True, default='avatars/default-avatar.png', null=True, upload_to='avatars/')),
                ('active_status', models.BooleanField(default=True)),
                ('primary_speciality', models.CharField(max_length=50)),
                ('associated_hospital', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_doctors', to='hospital.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
