# Generated by Django 4.2.4 on 2023-11-17 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0014_hospitaladmin_active_status"),
        ("doctor", "0019_alter_doctor_associated_hospital"),
        ("user", "0013_doctor_reviews_posted_hospital_reviews_posted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor_reviews",
            old_name="likes",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="hospital_reviews",
            old_name="likes",
            new_name="title",
        ),
        migrations.AddField(
            model_name="doctor_reviews",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.doctor",
            ),
        ),
        migrations.AddField(
            model_name="hospital_reviews",
            name="hospital",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.hospital",
            ),
        ),
    ]
