# Generated by Django 4.2.4 on 2023-11-17 04:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_alter_doctor_reviews_doctor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor_reviews",
            name="doctor_name",
        ),
        migrations.RemoveField(
            model_name="hospital_reviews",
            name="hospital_name",
        ),
    ]
