# Generated by Django 4.2.4 on 2023-10-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_remove_hospital_nta"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Name", max_length=100)),
                ("phone", models.CharField(default="000-000-0000", max_length=15)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                (
                    "borough",
                    models.CharField(
                        choices=[
                            ("BKN", "Brooklyn"),
                            ("MHT", "Manhattan"),
                            ("QNS", "Queens"),
                            ("BRX", "Bronx"),
                            ("SND", "Staten Island"),
                        ],
                        max_length=50,
                    ),
                ),
                ("zip", models.IntegerField()),
                ("associated_hospital", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        default="example@example.com", max_length=254, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="hospitalappointment",
            name="user",
        ),
    ]
