# Generated by Django 4.2.4 on 2023-10-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_patient_delete_user"),
        ("hospital", "0004_hospitaladmin_remove_hospitalappointment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalappointment",
            name="patient",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.patient",
            ),
        ),
    ]
