# Generated by Django 4.2.4 on 2023-10-22 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_patient_delete_user"),
        ("hospital", "0005_hospitalappointment_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalappointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.patient"
            ),
        ),
    ]
