# Generated by Django 4.2.4 on 2023-10-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0007_alter_hospitaladmin_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitaladmin",
            name="email",
            field=models.EmailField(
                default="example@example.com", max_length=254, unique=True
            ),
        ),
    ]
