# Generated by Django 4.2.4 on 2023-10-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0008_alter_hospitaladmin_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitaladmin",
            name="associated_hospital",
            field=models.ForeignKey(
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.hospital",
            ),
        ),
    ]
