# Generated by Django 4.2.3 on 2023-11-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_hospitalappointment_cancel_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaladmin',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
