# Generated by Django 4.2.4 on 2023-10-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0002_remove_doctorappointment_end_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="practice_mailing_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="practice_borough",
            new_name="borough",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="practice_phone_number",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="practice_zip_code",
            new_name="zip",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="organization_type",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="practice_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="site_name",
        ),
        migrations.AddField(
            model_name="doctor",
            name="hospital",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
