# Generated by Django 4.2.4 on 2023-10-18 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_remove_hospital_nta"),
        ("doctor", "0004_alter_doctor_borough"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="hospital",
            field=models.ForeignKey(
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.hospital",
            ),
        ),
    ]
