# Generated by Django 4.2.4 on 2023-10-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0005_alter_doctor_hospital"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorappointment",
            name="user",
        ),
        migrations.AddField(
            model_name="doctor",
            name="name",
            field=models.CharField(default="Default Name", max_length=100),
        ),
        migrations.AddField(
            model_name="doctor",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
