# Generated by Django 4.2.4 on 2023-10-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_patient_delete_user"),
        ("doctor", "0006_remove_doctorappointment_user_doctor_name_doctor_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorappointment",
            name="patient",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.patient",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="phone",
            field=models.CharField(default="000-000-0000", max_length=15),
        ),
    ]
