# Generated by Django 4.2.4 on 2023-10-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0008_alter_doctorappointment_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
    ]
