# Generated by Django 4.2.4 on 2023-10-22 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0009_doctor_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="last_name",
        ),
    ]
