# Generated by Django 4.2.4 on 2023-10-23 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0011_alter_doctor_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="hospital",
            new_name="associated_hospital",
        ),
    ]
