# Generated by Django 4.2.5 on 2023-11-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0015_doctorappointment_cancel_msg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorappointment",
            name="cancel_msg",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
