name: Autoformat with Black and Push Changes

on:
  push:
    paths:
      - '**.py'  # Trigger only when Python files are modified
    branches:
      - '*'  # Trigger on any branch

jobs:
  autoformat-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check code formatting with Black
        run: black --check . --skip-string-normalization
        continue-on-error: true # Continue even if Black check fails

      - name: Format code with Black (if check fails)
        run: black .
        if: failure() # Run this step only if the previous step fails

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
        if: failure()

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Autoformat code with Black"
          git push
        if: failure()
